# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/lukaj/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-820-DESKTOP-C4DB52S/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.cache/wt [current_project]
set_property parent.project_path D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo d:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/tanh_data.mem
read_verilog -library xil_defaultlib {
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/comparator2.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/control_logic2.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/convolver.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/input_mux.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/mac_manual.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/max_reg.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/pooler.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/qadd.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/qmult.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/relu.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/tanh_lut.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/variable_shift_reg.v
  D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/sources_1/new/accelerator.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/constrs_1/new/pynq_z2_constrains.xdc
set_property used_in_implementation false [get_files D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.srcs/constrs_1/new/pynq_z2_constrains.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top acclerator -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef acclerator.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file acclerator_utilization_synth.rpt -pb acclerator_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
