webtalk_init -webtalk_dir D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.sim/sim_1/behav/xsim/xsim.dir/accelerator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 20 03:53:02 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ca37af2-d05c-4af0-aab6-f51fd83d3f69" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fa1616ce28494c0882915742690beafa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Athlon(tm) II X4 631 Quad-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2595 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "920 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6712_KB" -context "xsim\\usage"
webtalk_transmit -clientid 959418941 -regid "" -xml D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.sim/sim_1/behav/xsim/xsim.dir/accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.sim/sim_1/behav/xsim/xsim.dir/accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Konacan_projekat_vivado/fpga-ml-accelerator/fpga-ml-accelerator.sim/sim_1/behav/xsim/xsim.dir/accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
